input_channel: 3

depth_multiple: 1.0
width_multiple: 1.0

#EfficientNetV2 yaml backbone
backbone:
    [
        [1, Conv, [24, 3, 2]],
        [1, FusedMBConv, [1,24,1,3]],
        [2, FusedMBConv, [4,48,2,3]],
        [2, FusedMBConv, [4,64,2,3]],
        [3, MBConv, [4,128,2,3]],
        [4, MBConv, [4,160,1,3]],
        [7, MBConv, [4,272,2,3]],
        [1, Conv, [1792, 1, 1]],
        [1, GlobalAvgPool, []],
        [1, Flatten, []],
        [1, Linear, [6]]
    ]
