input_channel: 3

depth_multiple: 1.0
width_multiple: 1.0

backbone:
    # Example model in PyTorch Tutorial (https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html)
    # [repeat, module, args]
    [
        [1, Conv, [32, 5, 3, null, 1, "HardSwish"]],
        # [1, InvertedResidualv3, [32, 6, 32, 3, 2, 1]],
        [1, Conv, [64, 3, 2, null, 1, "HardSwish"]],
        [1, Bottleneck, [64, 64]],
        [1, Bottleneck, [64, 64]],
        # [1, Bottleneck, [128, 128]],
        # [1, Bottleneck, [128, 128]],
        [1, InvertedResidualv3, [3, 3, 120, 0, 0, 1]],
        # [1, Bottleneck, [256, 256]],
        [1, Conv, [128, 3, 2]],
        [1, Conv, [128, 3, 2]],
        [1, DWConv, [256, 3, 2]],
        # [1, Conv, [128, 1, 1]],
        # [1, MaxPool, [2]],
        # [1, InvertedResidualv3, [3, 3, 120, 0, 0, 1]],
        # [1, DWConv, [512, 3, 2]],
        # [1, MaxPool, [2]],
        [1, GlobalAvgPool, []],
        [1, Flatten, []],
        # [1, Linear, [128]],
        [1, Linear, [6]]
    ]
