input_channel: 3

depth_multiple: 0.25
width_multiple: 1.0

backbone:
    # Example model in PyTorch Tutorial (https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html)
    # [repeat, module, args]
    [
        [1, DWConv, [64, 3, 1, null, "HardSwish"]],
        [4, InvertedResidualv2, [32, 4, 2]],
        [2, DWConv, [112, 3, 2, null, "HardSwish"]],
        [1, InvertedResidualv2, [56, 6, 2]],
        [2, InvertedResidualv2, [96, 4, 1]],
        [5, InvertedResidualv2, [64, 4, 1]],
        [4, DWConv, [512, 3, 2, null, "ReLU"]],
        [1, Conv, [256, 1, 1]],
        [1, GlobalAvgPool, []],
        [1, Flatten, []],
        [1, Linear, [6]]
    ]
