INPUT_SIZE:
- 224
- 224
backbone:
- - 2
  - Conv
  - - 64
    - 3
    - 1
    - null
    - 1
    - Hardswish
- - 2
  - Conv
  - - 48
    - 5
    - 2
    - null
    - 1
    - ReLU
- - 5
  - DWConv
  - - 240
    - 1
    - 2
    - null
    - ReLU
- - 5
  - InvertedResidualv2
  - - 32
    - 4
    - 2
- - 4
  - DWConv
  - - 480
    - 1
    - 2
    - null
    - Hardswish
- - 3
  - InvertedResidualv3
  - - 3
    - 1.6
    - 104
    - 0
    - 0
    - 1
- - 1
  - Conv
  - - 512
    - 1
    - 1
- - 1
  - GlobalAvgPool
  - []
- - 1
  - Flatten
  - []
- - 1
  - Linear
  - - 6
depth_multiple: 0.5
input_channel: 3
width_multiple: 0.75
