input_channel: 3

depth_multiple: 1.0
width_multiple: 1.0

#SqueezeNet
backbone:
    [
        [1, Conv, [96,7,2]],
        [1,MaxPool,[3,2,0,1,False,True]],
        [1,Fire,[16,64,64]],
        [1,Fire,[16,64,64]],
        [1,Fire,[32,128,128]],
        [1,MaxPool,[3,2,0,1,False,True]],
        [1,Fire,[32,128,128]],
        [1,Fire,[48,192,192]],
        [1,Fire,[48,192,192]],
        [1,Fire,[64,256,256]],
        [1,MaxPool,[3,2,0,1,False,True]],
        [1,Fire,[64,256,256]],
        [1,Dropout,[0.5]],
        [1,FixedConv,[1000,1,1]],
        [1,GlobalAvgPool,[]],
        [1,Flatten,[]],
        [1,Linear,[6]]
    ]
